services:
  mongo:
    build: ./mongodb_rs
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
