services:
  mongo:
    image: daviddev0508/polgo-mongo:${IMAGE_TAG:-latest}
    build: ./mongodb_rs
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27017
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: daviddev0508/polgo-backend:${IMAGE_TAG:-latest}
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      PORT: 3333
      DATABASE_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/${MONGO_DB}?authSource=admin&replicaSet=rs0
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    image: daviddev0508/polgo-frontend:${IMAGE_TAG:-latest}
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
